### ISSUE TITLE
error TS2307: Cannot find module '../version' or its corresponding type declarations

### ISSUE THREAD

**Issue by gosuto-inzasheru** [gelatodigital/web3-functions-sdk#96]
https://github.com/gelatodigital/web3-functions-sdk/blob/c653bd371debcac270e9b852f44b7d5684d1ad15/src/lib/builder/Web3FunctionBuilder.ts#L8

getting an error on this using a fresh clone:
```
$ yarn install
$ yarn test src/web3-functions/index.ts
```
```
yarn run v1.22.19
$ ts-node src/bin/index.ts test src/web3-functions/index.ts
/Users/gosuto/Documents/web3-functions-sdk/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/lib/builder/Web3FunctionBuilder.ts:8:29 - error TS2307: Cannot find module '../version' or its corresponding type declarations.

8 import { SDK_VERSION } from "../version";
                              ~~~~~~~~~~~~

    at createTSError (/Users/gosuto/Documents/web3-functions-sdk/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/Users/gosuto/Documents/web3-functions-sdk/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/Users/gosuto/Documents/web3-functions-sdk/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/Users/gosuto/Documents/web3-functions-sdk/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/Users/gosuto/Documents/web3-functions-sdk/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/gosuto/Documents/web3-functions-sdk/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  diagnosticCodes: [ 2307 ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by goums** [comment]
Hey, have you tried running `yarn build` before ` yarn test src/web3-functions/index.ts`?

**Comment by gosuto-inzasheru** [comment]
ah yea this is what was missing

i just followed the readme, which only mentions `yarn install` and `yarn test`

**Comment by gosuto-inzasheru** [comment]
would be nice to update the readme and add this to the instructions i guess

**Comment by goums** [comment]
Indeed, I forgot to reply here but it was added to the readme on today's release:
https://github.com/gelatodigital/web3-functions-sdk?tab=readme-ov-file#project-setup
